function meta = defaultMeta()
    meta = struct(...
        'exp', '',...
        'plateIndex', 1,...
        'wellRow', 'A',...
        'wellCol', 1,...
        'field', 1,...
        'sizeX', 1,...
        'sizeY', 1,...
        'sizeZ', 1,...
        'sizeT', 1,...
        'sizeC', 1,...
        'pixelSizeX', 1,...
        'pixelSizeY', 1,...
        'pixelSizeZ', 1,...
        'pixelSizeT', 1,...
        'bitDepth', 'uint16',...
        'dimsOrder', 'ctz',...
		'unit', 'um'...
        );
end

